### ISSUE TITLE
Local에서 테스트를 작동시키기 위해 aws환경과의 의존성을 분리해야 한다

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#46]
`application.yml` 파일 분리를 진행해야 함.
분리하는 과정에서 설정들의 정리도 함께 진행해보려고 합니다.

**Comment by wannte** [comment]
```yaml
spring:
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  ```

`use-new-id-generator-mappings: false` 부분은 entity 생성 방법 중 IDENTITY를 사용하는 것으로 보임! -> Entity에서 해당 정보를 직접 결정할 수 있도록 수정
