### ISSUE TITLE
12/5 CI/CD

### ISSUE THREAD

**Issue by ChoiEungi** [GIST-Petition-Site-Project/GIST-petition-server#66]
- reformatting할 시에, rearrange 하지 않기 코드

### EC2 Port 변경

<img src="https://user-images.githubusercontent.com/70755947/144739862-caa6afd9-3e76-4ec5-9197-b1568e31d015.png">

- spirng에서 port를 변경할 수 있다.
- Nginx 사용해서 80번 포트를 열 수 있다.
    1. 메모리도 먹어서 더 안좋아 보일 수 있지만, EC2에서 Spring서버를 확장할 때 편리하다. 이를 통해 무중단 배포를 진행할 수 있다. → 확장 가능한 구조를 만들 수 있다. 
    2. 443 포트로 들어오면 HTTPS로 동작하게 끔 기본 setting이 돼있다고 했음. 다만 HTTPS로 들어가게 만들 수 있다. NGINX가 자체적으로 HTTPS를 해독해서 해독한 정보를 스프링에 전달해주고 스프링의 정보를 암호화해서 클라이언트에 보내줄 수 있다.  → HTTPS에 대한 요구사항이 생길 때 유연하게 대처할 수 있다. → 결국 포트를 입력하지 않아도 spirng server로 mapping해줄 수 있다.
    3. NGINX EC2를 하나 띄우고 스프링 서버로 쓰는 EC2를 여러개 띄울 때 로드밸런싱을 진행할 수 있다.
    

AWS Elastic load Balancer를 사용할 수도 있는게 아닌가?(창하)

### Nginx

docker install cli
```
sudo apt-get update && \
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
sudo apt-key fingerprint 0EBFCD88 && \
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
sudo apt-get update && \
sudo apt-get install -y docker-ce && \
sudo usermod -aG docker ubuntu && \
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
sudo chmod +x /usr/local/bin/docker-compose && \
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
```

nginx.conf
```
events {}

http {
  upstream app {
    server 172.17.0.1:8080;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://app;
    }
  }
}
```

Dockerfile
```
FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
```

`docker build -t petition/reverse-proxy .`

`docker un -d -p 80:80 petition/reverse-proxy`

-p를 안넣으면 PORTS가 달라진다. 

지금은 80 port에서 8080으로 간다. 

스프링 서버가 8080포트인데, 이를 외부에 접근하지 못하게 하는 것이 가장 좋다/

java build(gradlew) → 

java -jar도 오래걸림

### CI

`./gradlew build` 

githhub action에서 `petition-CI.yml` 생성

- merge를 하기 위해 테스트를 진행해 조건을 확인한다.
- 이제는 테스트를 잘 작성하는 것이 중요해졌음

**ship show ask** 협업 방식

만약 Test가 잘 짜여있다면 PR 없이 커밋을 진행해볼 수 있다.

<br>

### 최종 CI 파일 (petition-CI.yml)

```
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build
```

### CD

code deploy를 이용해 ec2에 넘겨준다?

- 그냥 jar를 ec2에 올려서 실행하면 되는 것이 아닐까?

`scp` 를 이용하는방법

<img src="https://user-images.githubusercontent.com/70755947/144739905-8be7ebc0-a9b1-4308-8671-68f724369685.png">

Github Setting에서 secret key 관리해야 함.

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "*.md"
          target: "/home/ubuntu/test"

      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: pwd > /home/ubuntu/test/asd
```

 strip_components - remove the specified number of leading path elements. → 이로 인해 파일 전송이 안되는 것이었음. source에 leading path가 없음에도 파일 경로를 지워버렸음.

<br>

### 최종 CD file(petition-CD.yml)

```
name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Build App
        run: ./gradlew bootJar

      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/deploy"
          strip_components: 2
          
      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "deploy.sh"
          target: "/home/ubuntu/deploy"

      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: chmod +x /home/ubuntu/deploy/deploy.sh && sh /home/ubuntu/deploy/deploy.sh
```

```bash
#!/bin/bash
 echo "> now ing app pid find!"
 CURRENT_PID=$(pgrep -f gist-competition)
 echo "$CURRENT_PID"
 if [ -z $CURRENT_PID ]; then
         echo "> no ing app."
 else
         echo "> kill -9 $CURRENT_PID"
         kill -9 $CURRENT_PID
         sleep 3
 fi
 echo "> new app deploy"

 cd /home/ubuntu/deploy
 JAR_NAME=$(ls | grep 'gist-competition' | tail -n 1)
 echo "> JAR Name: $JAR_NAME"

 nohup java -jar -Duser.timezone=Asia/Seoul $JAR_NAME &
 sleep 2
```
